### PR TITLE
Week 2 pdf

### PR DESCRIPTION
**Pull request by omer-faruk-erdem**

### CODE REVIEW

**Review by muratbiberoglu — CHANGES_REQUESTED** [review]
- At slide 4's chart "nothing to worry about" is not formal phrase
- At slide 5, you can put "Start from second element!.." above of the image
- At slide 6, there is unnecessary "Start from second element!.."
- At slide 8, you can correct "sub array" to "subarray"
- At the end of slide 8, you can put spaces between words at "itisnotsuitableforlargedatasets"
- At slide 17, if number of elements in an array is odd, left subarray must be greater than right subarray. 
- At slide 17, last step, merge part, is wrong. Result must be {4, 9, 1, 3, 7, 15}
- At slide 18, Quick Sort's and Pivot's definitions are insufficient.
- At slide 18, "today" is unnecessary.
- At slide 19, "This process continued until we looked at every element of the array." is wrong. We are looking until pivot, not every element.
- At slide 29, cells' alignment are incompatible.

**Review by rojenarda — CHANGES_REQUESTED** [review]
- Slide 7: Code could be formatted for better readability. 
	Ex: "for (int i=1;i<v.size();i++)" ==> "for (int i = 1; i < v.size(); i++)"
 - Slide 11: Instead of writing your own swap function, you could use STL's std::swap. This way you can also demonstrate the usage of std::swap to the students.
 - Slide 21: Given space complexity of O(log(n)) is not correct. Quicksort sorts the array in-place, therefore no extra memory. 
  - Slide 29: Missing parantheses.
  * You could talk about why quicksort is usually preferred over mergesort, its advantages and disadvanteges.

**Comment by hacerakinci** [comment]
Slide 19:  at line 3 "Left vector" should be "LEFT vector", and at line 9, you can put a space between "RIGHTvectors".  
Slide 22:   There are spacing mistakes at last sentence.
Correct form: "There are different ways of choosing pivot: first element, last element, random element, median value."

**Review by muratbiberoglu — APPROVED** [review]

**Comment by muratbiberoglu** [comment]
Added slide for week 2

**Pull request merged**
